name: build

on:
  pull_request:

permissions:
  contents: read

env:
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: default

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Test build
        run: go build ...
